const express = require("express")
const router = express.Router()
const adminModule = require("../module/admin")
const auth = require("../auth")

router.post('/register',adminModule.registerAdmin)
router.post('/login',adminModule.loginAdmin)
router.post('/create',auth,adminModule.createTheater)
router.put('/update',auth,adminModule.updateTheater)
router.get('/getTheater',auth,adminModule.getTheater)
router.get('/getTheater/:name',auth,adminModule.getTheaterByName)
router.get('/welcome',auth,adminModule.welcome)
router.get('/bookedShows',auth,adminModule.getBookedMovies)
router.get('/bookedShows/:theater/:movie/:date',auth,adminModule.getBookedMoviesD)
router.get('/theater',auth,adminModule.getTheater)
router.get('/theater/:name',auth,adminModule.getTheaterByName)
router.get('/movies',auth,adminModule.getMovies)
router.get('/movies/:name',auth,adminModule.getMoviesbyName)
router.get('/signout',adminModule.signout)
module.exports = router